[package]
name = "chrisomatic"
version = "0.1.0"
edition = "2024"

[dependencies]
chrisomatic_spec = { path = "../chrisomatic_spec" }
chrisomatic_core = { path = "../chrisomatic_core" }
toml = "0.9.2"
clap = { version = "4.5.41", features = ["derive"] }
color-eyre = "0.6.5"
